-- 코드를 입력하세요
SELECT FLAVOR
FROM (
    SELECT FLAVOR, TOTAL_ORDER FROM JULY
    UNION ALL
    SELECT FLAVOR, TOTAL_ORDER FROM FIRST_HALF
    ) AS R
GROUP BY FLAVOR
ORDER BY SUM(TOTAL_ORDER) DESC
LIMIT 3
